import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:image_picker/image_picker.dart';
import 'package:get_it/get_it.dart';
import 'dart:io';
import '../../domain/entities/pet.dart';
import '../../domain/usecases/get_current_shelter.dart';
import 'package:petadopt/features/pets/presentation/bloc/pet_form_bloc.dart';
import 'package:petadopt/features/pets/presentation/bloc/pet_form_event.dart';
import 'package:petadopt/features/pets/presentation/bloc/pet_form_state.dart';

class CreatePetPage extends StatefulWidget {
  const CreatePetPage({super.key});

  @override
  State<CreatePetPage> createState() => _CreatePetPageState();
}

class _CreatePetPageState extends State<CreatePetPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _breedController = TextEditingController();
  final _healthStatusController = TextEditingController();
  
  PetSpecies _selectedSpecies = PetSpecies.dog;
  PetSize _selectedSize = PetSize.medium;
  PetGender _selectedGender = PetGender.male;
  int _ageYears = 0;
  int _ageMonths = 0;
  
  final List<XFile> _selectedImages = [];
  final ImagePicker _picker = ImagePicker();
  
  late final PetFormBloc _petFormBloc;

  @override
  void initState() {
    super.initState();
    _petFormBloc = PetFormBloc(
      createPet: GetIt.instance(),
      updatePet: GetIt.instance(),
      uploadPetImages: GetIt.instance(),
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _breedController.dispose();
    _healthStatusController.dispose();
    _petFormBloc.close();
    super.dispose();
  }

  Future<void> _pickImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage(
        imageQuality: 85,
      );
      
      if (images.isNotEmpty) {
        setState(() {
          _selectedImages.addAll(images);
        });
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error al seleccionar imágenes: $e')),
        );
      }
    }
  }

  void _removeImage(int index) {
    setState(() {
      _selectedImages.removeAt(index);
    });
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      if (_selectedImages.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Por favor, selecciona al menos una imagen'),
            backgroundColor: Colors.orange,
          ),
        );
        return;
      }

      // Obtener el shelter_id del usuario autenticado
      final getShelter = GetIt.instance<GetCurrentShelter>();
      final result = await getShelter();
      
      String shelterId = '';
      result.fold(
        (failure) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(failure.message),
              backgroundColor: Colors.red,
            ),
          );
          return;
        },
        (id) => shelterId = id,
      );

      if (shelterId.isEmpty) {
        return;
      }

      final pet = Pet(
        id: '',  // Will be generated by backend
        shelterId: shelterId,
        name: _nameController.text.trim(),
        species: _selectedSpecies,
        breed: _breedController.text.trim().isEmpty 
            ? 'Desconocida' 
            : _breedController.text.trim(),
        ageYears: _ageYears,
        ageMonths: _ageMonths,
        gender: _selectedGender,
        size: _selectedSize,
        description: _descriptionController.text.trim(),
        personalityTraits: [],  // Can be added in a future update
        mainImageUrl: '',  // Will be set after upload
        imagesUrls: [],  // Will be set after upload
        isVaccinated: false,
        isDewormed: false,
        isSterilized: false,
        hasMicrochip: false,
        needsSpecialCare: false,
        healthNotes: _healthStatusController.text.trim().isEmpty
            ? null
            : _healthStatusController.text.trim(),
        adoptionStatus: AdoptionStatus.available,
        viewsCount: 0,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      _petFormBloc.add(CreatePetEvent(pet: pet, images: _selectedImages));
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: _petFormBloc,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Agregar Mascota'),
        ),
        body: BlocConsumer<PetFormBloc, PetFormState>(
          listener: (context, state) {
            if (state is PetFormSuccess) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(state.message),
                  backgroundColor: Colors.green,
                ),
              );
              Navigator.of(context).pop(true);
            } else if (state is PetFormError) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(state.message),
                  backgroundColor: Colors.red,
                ),
              );
            } else if (state is PetFormUploading) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text('${state.message} ${(state.progress * 100).toInt()}%'),
                  duration: const Duration(seconds: 1),
                ),
              );
            }
          },
          builder: (context, state) {
            final isLoading = state is PetFormLoading || state is PetFormUploading;

            return Stack(
              children: [
                SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: Form(
                    key: _formKey,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Images Section
                        const Text(
                          'Fotos',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 8),
                        _buildImagePicker(),
                        const SizedBox(height: 24),

                        // Basic Info
                        const Text(
                          'Información Básica',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 16),
                        
                        TextFormField(
                          controller: _nameController,
                          decoration: const InputDecoration(
                            labelText: 'Nombre *',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.pets),
                          ),
                          validator: (value) {
                            if (value == null || value.trim().isEmpty) {
                              return 'Por favor, ingresa el nombre';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 16),

                        DropdownButtonFormField<PetSpecies>(
                          value: _selectedSpecies,
                          decoration: const InputDecoration(
                            labelText: 'Especie *',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.category),
                          ),
                          items: PetSpecies.values.map((species) {
                            return DropdownMenuItem(
                              value: species,
                              child: Text(species.displayName),
                            );
                          }).toList(),
                          onChanged: (value) {
                            if (value != null) {
                              setState(() => _selectedSpecies = value);
                            }
                          },
                        ),
                        const SizedBox(height: 16),

                        TextFormField(
                          controller: _breedController,
                          decoration: const InputDecoration(
                            labelText: 'Raza (opcional)',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.label),
                          ),
                        ),
                        const SizedBox(height: 16),

                        Row(
                          children: [
                            Expanded(
                              child: DropdownButtonFormField<int>(
                                value: _ageYears,
                                decoration: const InputDecoration(
                                  labelText: 'Años',
                                  border: OutlineInputBorder(),
                                ),
                                items: List.generate(20, (index) => index)
                                    .map((age) => DropdownMenuItem(
                                          value: age,
                                          child: Text('$age años'),
                                        ))
                                    .toList(),
                                onChanged: (value) {
                                  if (value != null) {
                                    setState(() => _ageYears = value);
                                  }
                                },
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: DropdownButtonFormField<int>(
                                value: _ageMonths,
                                decoration: const InputDecoration(
                                  labelText: 'Meses',
                                  border: OutlineInputBorder(),
                                ),
                                items: List.generate(12, (index) => index)
                                    .map((months) => DropdownMenuItem(
                                          value: months,
                                          child: Text('$months meses'),
                                        ))
                                    .toList(),
                                onChanged: (value) {
                                  if (value != null) {
                                    setState(() => _ageMonths = value);
                                  }
                                },
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 16),

                        DropdownButtonFormField<PetSize>(
                          value: _selectedSize,
                          decoration: const InputDecoration(
                            labelText: 'Tamaño *',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.straighten),
                          ),
                          items: PetSize.values.map((size) {
                            return DropdownMenuItem(
                              value: size,
                              child: Text(size.displayName),
                            );
                          }).toList(),
                          onChanged: (value) {
                            if (value != null) {
                              setState(() => _selectedSize = value);
                            }
                          },
                        ),
                        const SizedBox(height: 16),

                        DropdownButtonFormField<PetGender>(
                          value: _selectedGender,
                          decoration: const InputDecoration(
                            labelText: 'Género *',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.male),
                          ),
                          items: PetGender.values.map((gender) {
                            return DropdownMenuItem(
                              value: gender,
                              child: Text(gender.displayName),
                            );
                          }).toList(),
                          onChanged: (value) {
                            if (value != null) {
                              setState(() => _selectedGender = value);
                            }
                          },
                        ),
                        const SizedBox(height: 24),

                        // Description
                        const Text(
                          'Descripción',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 8),
                        TextFormField(
                          controller: _descriptionController,
                          decoration: const InputDecoration(
                            labelText: 'Descripción *',
                            border: OutlineInputBorder(),
                            hintText: 'Cuéntanos sobre esta mascota...',
                          ),
                          maxLines: 5,
                          validator: (value) {
                            if (value == null || value.trim().isEmpty) {
                              return 'Por favor, ingresa una descripción';
                            }
                            if (value.trim().length < 20) {
                              return 'La descripción debe tener al menos 20 caracteres';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 16),

                        TextFormField(
                          controller: _healthStatusController,
                          decoration: const InputDecoration(
                            labelText: 'Estado de Salud (opcional)',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.medical_services),
                            hintText: 'Ej: Vacunas al día, esterilizado',
                          ),
                          maxLines: 3,
                        ),
                        const SizedBox(height: 32),

                        // Submit Button
                        SizedBox(
                          width: double.infinity,
                          height: 50,
                          child: ElevatedButton(
                            onPressed: isLoading ? null : _submitForm,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Theme.of(context).primaryColor,
                              foregroundColor: Colors.white,
                            ),
                            child: Text(
                              isLoading ? 'Creando...' : 'Crear Mascota',
                              style: const TextStyle(fontSize: 16),
                            ),
                          ),
                        ),
                        const SizedBox(height: 16),
                      ],
                    ),
                  ),
                ),
                if (isLoading)
                  Container(
                    color: Colors.black54,
                    child: const Center(
                      child: CircularProgressIndicator(),
                    ),
                  ),
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildImagePicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (_selectedImages.isEmpty)
          GestureDetector(
            onTap: _pickImages,
            child: Container(
              height: 200,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey),
                borderRadius: BorderRadius.circular(8),
                color: Colors.grey[100],
              ),
              child: const Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.add_photo_alternate, size: 64, color: Colors.grey),
                    SizedBox(height: 8),
                    Text(
                      'Toca para agregar fotos',
                      style: TextStyle(color: Colors.grey),
                    ),
                  ],
                ),
              ),
            ),
          )
        else
          Column(
            children: [
              SizedBox(
                height: 120,
                child: ListView.builder(
                  scrollDirection: Axis.horizontal,
                  itemCount: _selectedImages.length + 1,
                  itemBuilder: (context, index) {
                    if (index == _selectedImages.length) {
                      return GestureDetector(
                        onTap: _pickImages,
                        child: Container(
                          width: 120,
                          margin: const EdgeInsets.only(right: 8),
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey),
                            borderRadius: BorderRadius.circular(8),
                            color: Colors.grey[100],
                          ),
                          child: const Icon(Icons.add, size: 48, color: Colors.grey),
                        ),
                      );
                    }

                    return Stack(
                      children: [
                        Container(
                          width: 120,
                          margin: const EdgeInsets.only(right: 8),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(8),
                            image: DecorationImage(
                              image: FileImage(File(_selectedImages[index].path)),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                        Positioned(
                          top: 4,
                          right: 12,
                          child: GestureDetector(
                            onTap: () => _removeImage(index),
                            child: Container(
                              padding: const EdgeInsets.all(4),
                              decoration: const BoxDecoration(
                                color: Colors.red,
                                shape: BoxShape.circle,
                              ),
                              child: const Icon(
                                Icons.close,
                                color: Colors.white,
                                size: 16,
                              ),
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
              const SizedBox(height: 8),
              Text(
                '${_selectedImages.length} foto(s) seleccionada(s)',
                style: TextStyle(color: Colors.grey[600]),
              ),
            ],
          ),
      ],
    );
  }
}
